### ISSUE TITLE
licenseKey is required for fullPage.js

### ISSUE THREAD

**Issue by Plunzi** [kendlbat/kendlbat.dev#1]
![image](https://user-images.githubusercontent.com/62830040/233783181-fcaf3509-876b-4b13-ae65-73e93c74bdc7.png)
Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:
https://github.com/alvarotrigo/fullPage.js#options

**Comment by kendlbat** [comment]
Will not be fixed as old portfolio is in the process of being deprecated.
Please see https://kendlbat.dev/beta for a preview of the replacement.
